#------------------------------------------------------------------------------
#
#  $Id$
#
#  Copyright (C) 2006-2008  Florian Pose, Ingenieurgemeinschaft IgH
#
#  This file is part of the IgH EtherCAT Master.
#
#  The IgH EtherCAT Master is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License version 2, as
#  published by the Free Software Foundation.
#
#  The IgH EtherCAT Master is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with the IgH EtherCAT Master; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#  ---
#
#  The license mentioned above concerns the source code only. Using the
#  EtherCAT technology and brand is only permitted in compliance with the
#  industrial property and similar rights of Beckhoff Automation GmbH.
#
#  ---
#
#  vim: syntax=make
#
#------------------------------------------------------------------------------

TOPDIR := $(src)/../..

REV := $(shell if test -s $(TOPDIR)/revision; then \
		cat $(TOPDIR)/revision; \
	else \
		git -C $(TOPDIR) describe 2>/dev/null || echo "unknown"; \
	fi)

ifeq (1,1)
	EC_STMMAC_OBJ := \
		stmmac_main-5.10-ethercat.o \
		stmmac_mdio-5.10-ethercat.o \
		dwmac_lib-5.10-ethercat.o \
		mmc_core-5.10-ethercat.o \
		dwmac4_descs-5.10-ethercat.o \
		dwmac4_dma-5.10-ethercat.o \
		dwmac4_lib-5.10-ethercat.o \
		dwmac4_core-5.10-ethercat.o \
		hwif-5.10-ethercat.o \
		ring_mode-5.10-ethercat.o \
		chain_mode-5.10-ethercat.o \
		dwmac1000_core-5.10-ethercat.o \
		dwmac1000_dma-5.10-ethercat.o \
		dwmac100_core-5.10-ethercat.o \
		dwmac100_dma-5.10-ethercat.o \
		enh_desc-5.10-ethercat.o \
		norm_desc-5.10-ethercat.o \
		dwmac5-5.10-ethercat.o \
		stmmac_tc-5.10-ethercat.o \
		dwxgmac2_core-5.10-ethercat.o \
		dwxgmac2_dma-5.10-ethercat.o \
		dwxgmac2_descs-5.10-ethercat.o \
		stmmac_ethtool-5.10-ethercat.o \
		stmmac_hwtstamp-5.10-ethercat.o \
		stmmac_ptp-5.10-ethercat.o \
		stmmac_platform-5.10-ethercat.o \
		dwmac-rk-5.10-ethercat.o \
		stmmac_xdp-5.10-ethercat.o

	obj-m += ec_stmmac.o
	ec_stmmac-objs := $(EC_STMMAC_OBJ)
	CFLAGS_stmmac_main-5.10-ethercat.o = -DREV=$(REV)
endif

KBUILD_EXTRA_SYMBOLS := \
	/home/william/ethercat_igh/$(LINUX_SYMVERS) \
	/home/william/ethercat_igh/master/$(LINUX_SYMVERS)

#------------------------------------------------------------------------------
