#------------------------------------------------------------------------------
#
#  $Id$
#
#  Copyright (C) 2006-2008  Florian Pose, Ingenieurgemeinschaft IgH
#
#  This file is part of the IgH EtherCAT Master.
#
#  The IgH EtherCAT Master is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License version 2, as
#  published by the Free Software Foundation.
#
#  The IgH EtherCAT Master is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with the IgH EtherCAT Master; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#  ---
#
#  The license mentioned above concerns the source code only. Using the
#  EtherCAT technology and brand is only permitted in compliance with the
#  industrial property and similar rights of Beckhoff Automation GmbH.
#
#------------------------------------------------------------------------------
include $(top_srcdir)/Makefile.kbuild

EXTRA_DIST = \
	LICENSE \
altr_tse_pcs-4.19-ethercat.c \
altr_tse_pcs-4.19-orig.c \
altr_tse_pcs-4.19-ethercat.h \
altr_tse_pcs-4.19-orig.h \
chain_mode-4.19-ethercat.c \
chain_mode-4.19-orig.c \
common-4.19-ethercat.h \
common-4.19-orig.h \
descs-4.19-ethercat.h \
descs-4.19-orig.h \
descs_com-4.19-ethercat.h \
descs_com-4.19-orig.h \
ring_mode-4.19-ethercat.c \
ring_mode-4.19-orig.c \
dwmac1000-4.19-ethercat.h \
dwmac1000-4.19-orig.h \
dwmac1000_core-4.19-ethercat.c  \
dwmac1000_core-4.19-orig.c \
dwmac1000_dma-4.19-ethercat.c \
dwmac1000_dma-4.19-orig.c \
dwmac100-4.19-ethercat.h \
dwmac100-4.19-orig.h \
dwmac100_core-4.19-ethercat.c \
dwmac100_core-4.19-orig.c \
dwmac100_dma-4.19-ethercat.c \
dwmac100_dma-4.19-orig.c \
dwmac4_dma-4.19-ethercat.h \
dwmac4_dma-4.19-orig.h \
dwmac4_dma-4.19-ethercat.c \
dwmac4_dma-4.19-orig.c \
dwmac4_core-4.19-ethercat.c \
dwmac4_core-4.19-orig.c \
stmmac_mdio-4.19-ethercat.c \
stmmac_mdio-4.19-orig.c \
dwmac-rk-4.19-ethercat.c \
dwmac-rk-4.19-orig.c \
dwxgmac2-4.19-ethercat.h \
dwxgmac2-4.19-orig.h \
mmc-4.19-ethercat.h \
stmmac_pci-4.19-ethercat.c \
mmc-4.19-orig.h \
stmmac_pci-4.19-orig.c \
dwmac5-4.19-ethercat.h \
dwxgmac2_descs-4.19-orig.c \
norm_desc-4.19-orig.c \
stmmac_platform-4.19-ethercat.h \
dwmac4_lib-4.19-ethercat.c \
dwxgmac2_core-4.19-ethercat.c \
mmc_core-4.19-ethercat.c \
stmmac_pcs-4.19-ethercat.h \
dwmac4_lib-4.19-orig.c \
dwxgmac2_core-4.19-orig.c \
mmc_core-4.19-orig.c \
stmmac_pcs-4.19-orig.h \
dwmac4-4.19-ethercat.h \
dwmac5-4.19-orig.c \
dwxgmac2_dma-4.19-ethercat.c \
stmmac_platform-4.19-orig.c \
dwmac4-4.19-orig.h \
dwmac5-4.19-orig.h \
dwxgmac2_dma-4.19-orig.c \
stmmac_platform-4.19-orig.h \
dwmac_dma-4.19-ethercat.h \
enh_desc-4.19-ethercat.c \
stmmac-4.19-ethercat.h \
stmmac_ptp-4.19-ethercat.c \
dwmac_dma-4.19-orig.h \
enh_desc-4.19-orig.c \
stmmac-4.19-orig.h \
stmmac_ptp-4.19-ethercat.h \
dwmac5-4.19-ethercat.c \
dwxgmac2_descs-4.19-ethercat.c \
norm_desc-4.19-ethercat.c \
stmmac_platform-4.19-ethercat.c \
dwmac4_descs-4.19-ethercat.c \
dwmac-generic-4.19-ethercat.c \
hwif-4.19-ethercat.c \
stmmac_hwtstamp-4.19-ethercat.c \
stmmac_ptp-4.19-orig.c \
dwmac4_descs-4.19-ethercat.h \
dwmac-generic-4.19-orig.c \
hwif-4.19-ethercat.h \
stmmac_hwtstamp-4.19-orig.c \
stmmac_ptp-4.19-orig.h \
dwmac4_descs-4.19-orig.c \
dwmac_lib-4.19-ethercat.c \
hwif-4.19-orig.c \
stmmac_main-4.19-ethercat.c \
stmmac_tc-4.19-ethercat.c \
dwmac4_descs-4.19-orig.h \
dwmac_lib-4.19-orig.c \
hwif-4.19-orig.h \
stmmac_main-4.19-orig.c \
stmmac_tc-4.19-orig.c \
altr_tse_pcs-5.10-ethercat.c \
altr_tse_pcs-5.10-orig.c \
altr_tse_pcs-5.10-ethercat.h \
altr_tse_pcs-5.10-orig.h \
chain_mode-5.10-ethercat.c \
chain_mode-5.10-orig.c \
common-5.10-ethercat.h \
common-5.10-orig.h \
descs-5.10-ethercat.h \
descs-5.10-orig.h \
descs_com-5.10-ethercat.h \
descs_com-5.10-orig.h \
ring_mode-5.10-ethercat.c \
ring_mode-5.10-orig.c \
dwmac1000-5.10-ethercat.h \
dwmac1000-5.10-orig.h \
dwmac1000_core-5.10-ethercat.c  \
dwmac1000_core-5.10-orig.c \
dwmac1000_dma-5.10-ethercat.c \
dwmac1000_dma-5.10-orig.c \
dwmac100-5.10-ethercat.h \
dwmac100-5.10-orig.h \
dwmac100_core-5.10-ethercat.c \
dwmac100_core-5.10-orig.c \
dwmac100_dma-5.10-ethercat.c \
dwmac100_dma-5.10-orig.c \
dwmac4_dma-5.10-ethercat.h \
dwmac4_dma-5.10-orig.h \
dwmac4_dma-5.10-ethercat.c \
dwmac4_dma-5.10-orig.c \
dwmac4_core-5.10-ethercat.c \
dwmac4_core-5.10-orig.c \
stmmac_mdio-5.10-ethercat.c \
stmmac_mdio-5.10-orig.c \
dwmac-rk-5.10-ethercat.c \
dwmac-rk-5.10-orig.c \
mmc-5.10-ethercat.h \
stmmac_pci-5.10-ethercat.c \
mmc-5.10-orig.h \
stmmac_pci-5.10-orig.c \
dwmac5-5.10-ethercat.h \
norm_desc-5.10-orig.c \
stmmac_platform-5.10-ethercat.h \
dwmac4_lib-5.10-ethercat.c \
mmc_core-5.10-ethercat.c \
stmmac_pcs-5.10-ethercat.h \
dwmac4_lib-5.10-orig.c \
mmc_core-5.10-orig.c \
stmmac_pcs-5.10-orig.h \
dwmac4-5.10-ethercat.h \
dwmac5-5.10-orig.c \
stmmac_platform-5.10-orig.c \
dwmac4-5.10-orig.h \
dwmac5-5.10-orig.h \
stmmac_platform-5.10-orig.h \
dwmac_dma-5.10-ethercat.h \
enh_desc-5.10-ethercat.c \
stmmac-5.10-ethercat.h \
stmmac_ptp-5.10-ethercat.c \
dwmac_dma-5.10-orig.h \
enh_desc-5.10-orig.c \
stmmac-5.10-orig.h \
stmmac_ptp-5.10-ethercat.h \
dwmac5-5.10-ethercat.c \
dwxgmac2_descs-5.10-ethercat.c \
norm_desc-5.10-ethercat.c \
stmmac_platform-5.10-ethercat.c \
dwmac4_descs-5.10-ethercat.c \
dwmac-generic-5.10-ethercat.c \
hwif-5.10-ethercat.c \
stmmac_hwtstamp-5.10-ethercat.c \
stmmac_ptp-5.10-orig.c \
dwmac4_descs-5.10-ethercat.h \
dwmac-generic-5.10-orig.c \
hwif-5.10-ethercat.h \
stmmac_hwtstamp-5.10-orig.c \
stmmac_ptp-5.10-orig.h \
dwmac4_descs-5.10-orig.c \
dwmac_lib-5.10-ethercat.c \
hwif-5.10-orig.c \
stmmac_main-5.10-ethercat.c \
stmmac_tc-5.10-ethercat.c \
dwmac4_descs-5.10-orig.h \
dwmac_lib-5.10-orig.c \
hwif-5.10-orig.h \
stmmac_main-5.10-orig.c \
stmmac_tc-5.10-orig.c \
altr_tse_pcs-6.1-ethercat.c \
altr_tse_pcs-6.1-ethercat.h \
altr_tse_pcs-6.1-orig.c \
altr_tse_pcs-6.1-orig.h \
chain_mode-6.1-ethercat.c \
chain_mode-6.1-orig.c \
dwmac1000_dma-6.1-ethercat.c \
dwmac4_dma-6.1-ethercat.c \
dwmac_lib-6.1-ethercat.c \
ring_mode-6.1-ethercat.c \
stmmac_platform-6.1-ethercat.c \
dwmac1000_dma-6.1-orig.c \
dwmac4_dma-6.1-ethercat.h \
dwmac_lib-6.1-orig.c \
ring_mode-6.1-orig.c \
stmmac_platform-6.1-ethercat.h \
dwmac100-6.1-ethercat.h \
dwmac4_dma-6.1-orig.c \
dwmac-rk-6.1-ethercat.c \
stmmac-6.1-ethercat.h \
stmmac_platform-6.1-orig.c \
dwmac100-6.1-orig.h \
dwmac4_dma-6.1-orig.h \
dwmac-rk-6.1-orig.c \
stmmac-6.1-orig.h \
stmmac_platform-6.1-orig.h \
dwmac100_core-6.1-ethercat.c \
dwmac4_lib-6.1-ethercat.c \
enh_desc-6.1-ethercat.c \
stmmac_ethtool-6.1-ethercat.c \
stmmac_ptp-6.1-ethercat.c \
dwmac100_core-6.1-orig.c \
dwmac4_lib-6.1-orig.c \
enh_desc-6.1-orig.c \
stmmac_ethtool-6.1-orig.c \
stmmac_ptp-6.1-ethercat.h \
common-6.1-ethercat.h \
dwmac100_dma-6.1-ethercat.c \
dwmac5-6.1-ethercat.c \
hwif-6.1-ethercat.c \
stmmac_hwtstamp-6.1-ethercat.c \
stmmac_ptp-6.1-orig.c \
common-6.1-orig.h \
dwmac100_dma-6.1-orig.c \
dwmac5-6.1-ethercat.h \
hwif-6.1-ethercat.h \
stmmac_hwtstamp-6.1-orig.c \
stmmac_ptp-6.1-orig.h \
descs-6.1-ethercat.h \
dwmac4-6.1-ethercat.h \
dwmac5-6.1-orig.c \
hwif-6.1-orig.c \
stmmac_main-6.1-ethercat.c \
stmmac_tc-6.1-ethercat.c \
descs-6.1-orig.h \
dwmac4-6.1-orig.h \
dwmac5-6.1-orig.h \
hwif-6.1-orig.h \
stmmac_main-6.1-orig.c \
stmmac_tc-6.1-orig.c \
descs_com-6.1-ethercat.h \
dwmac4_core-6.1-ethercat.c \
dwmac-anarion-6.1-ethercat.c \
mmc-6.1-ethercat.h \
stmmac_mdio-6.1-ethercat.c \
stmmac_xdp-6.1-ethercat.c \
descs_com-6.1-orig.h \
dwmac4_core-6.1-orig.c \
dwmac-anarion-6.1-orig.c \
mmc-6.1-orig.h \
stmmac_mdio-6.1-orig.c \
stmmac_xdp-6.1-ethercat.h \
dwmac1000-6.1-ethercat.h \
dwmac4_descs-6.1-ethercat.c \
dwmac_dma-6.1-ethercat.h \
mmc_core-6.1-ethercat.c \
stmmac_pci-6.1-ethercat.c \
stmmac_xdp-6.1-orig.c \
dwmac1000-6.1-orig.h \
dwmac4_descs-6.1-ethercat.h \
dwmac_dma-6.1-orig.h \
mmc_core-6.1-orig.c \
stmmac_pci-6.1-orig.c \
stmmac_xdp-6.1-orig.h \
dwmac1000_core-6.1-ethercat.c \
dwmac4_descs-6.1-orig.c \
dwmac-generic-6.1-ethercat.c \
norm_desc-6.1-ethercat.c \
stmmac_pcs-6.1-ethercat.h \
dwmac1000_core-6.1-orig.c \
dwmac4_descs-6.1-orig.h \
dwmac-generic-6.1-orig.c \
norm_desc-6.1-orig.c \
stmmac_pcs-6.1-orig.h

#------------------------------------------------------------------------------
